[package]
name = "foundry-config-spec"
description = "Foundry configuration specification"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
foundry-config.workspace = true
serde.workspace = true

# schema
schemars = { version = "1.0", optional = true }

[dev-dependencies]
serde_json.workspace = true

[features]
schema = ["dep:schemars", "foundry-config/schema"]
