[package]
name = "wasm-playground"
description = "WASM bindings for cast (browser-oriented)"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "Window", "Request", "RequestInit", "Response", "Headers", "RequestMode", "console"
] }

alloy-primitives = { version = "1.3.1", default-features = false, features = ["std", "serde"] }
alloy-dyn-abi = { version = "1.3.1", default-features = false, features = ["std"] }
alloy-json-abi = { version = "1.3.1", default-features = false }

getrandom = { version = "0.3.3", features = ["wasm_js"] }
getrandom_02 = { package = "getrandom", version = "0.2", features = ["js"] }
