[package]
name = "wasm-fmt-lint"
description = "WASM bindings for forge-fmt and (stub) forge-lint for browsers"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
js-sys = "0.3"

# Browser-friendly RNG backend
getrandom = { version = "0.3.3", features = ["wasm_js"] }
getrandom_02 = { package = "getrandom", version = "0.2", features = ["js"] }

# Foundry crates
forge-fmt = { path = "../crates/fmt" }

# Note: forge-lint brings in heavier deps and threading; we will add it later behind a feature.
# forge-lint = { path = "../crates/lint", optional = true }

[features]
# placeholder to enable lint later
lint = []

[profile.release]
lto = true
opt-level = 's'
panic = "abort"
codegen-units = 1
